/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChartsRouteImport } from './routes/charts'
import { Route as SearchRouteImport } from './routes/search'
import { Route as AlbumBrowseIdRouteImport } from './routes/album.$browseId'
import { Route as ArtistArtistIdRouteImport } from './routes/artist.$artistId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChartsRoute = ChartsRouteImport.update({
  id: '/charts',
  path: '/charts',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumBrowseIdRoute = AlbumBrowseIdRouteImport.update({
  id: '/album/$browseId',
  path: '/album/$browseId',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistArtistIdRoute = ArtistArtistIdRouteImport.update({
  id: '/artist/$artistId',
  path: '/artist/$artistId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/charts': typeof ChartsRoute
  '/search': typeof SearchRoute
  '/album/$browseId': typeof AlbumBrowseIdRoute
  '/artist/$artistId': typeof ArtistArtistIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/charts': typeof ChartsRoute
  '/search': typeof SearchRoute
  '/album/$browseId': typeof AlbumBrowseIdRoute
  '/artist/$artistId': typeof ArtistArtistIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/charts': typeof ChartsRoute
  '/search': typeof SearchRoute
  '/album/$browseId': typeof AlbumBrowseIdRoute
  '/artist/$artistId': typeof ArtistArtistIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/charts' | '/search' | '/album/$browseId' | '/artist/$artistId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/charts' | '/search' | '/album/$browseId' | '/artist/$artistId'
  id:
    | '__root__'
    | '/'
    | '/charts'
    | '/search'
    | '/album/$browseId'
    | '/artist/$artistId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChartsRoute: typeof ChartsRoute
  SearchRoute: typeof SearchRoute
  AlbumBrowseIdRoute: typeof AlbumBrowseIdRoute
  ArtistArtistIdRoute: typeof ArtistArtistIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charts': {
      id: '/charts'
      path: '/charts'
      fullPath: '/charts'
      preLoaderRoute: typeof ChartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/album/$browseId': {
      id: '/album/$browseId'
      path: '/album/$browseId'
      fullPath: '/album/$browseId'
      preLoaderRoute: typeof AlbumBrowseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artist/$artistId': {
      id: '/artist/$artistId'
      path: '/artist/$artistId'
      fullPath: '/artist/$artistId'
      preLoaderRoute: typeof ArtistArtistIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChartsRoute: ChartsRoute,
  SearchRoute: SearchRoute,
  AlbumBrowseIdRoute: AlbumBrowseIdRoute,
  ArtistArtistIdRoute: ArtistArtistIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
